---
version: '3.9'
x-common:
  database: &db-environment
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: &pg-user ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    TZ: ${TZ}
  backup: &backup-environment
    SCHEDULE: ${SCHEDULE}
    BACKUP_KEEP_DAYS: ${BACKUP_KEEP_DAYS}
    BACKUP_KEEP_WEEKS: ${BACKUP_KEEP_WEEKS}
    BACKUP_KEEP_MONTHS: ${BACKUP_KEEP_MONTHS}
  admin: &admin-environment
    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    PGADMIN_PORT: &pgadmin-port ${PGADMIN_PORT}
#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. 
# Please only make modifications
# below if you understand what you are doing.
#
services:
  postgres:
    container_name: resolve_pgsql
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      <<: [*db-environment]
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgbackups:
    container_name: resolve_pgbackup
    image: prodrigestivill/postgres-backup-local:13
    restart: always
    volumes:
      - ${BACKUP_PATH}:/backups
    depends_on:
      - postgres
    environment:
      <<: [*db-environment, *backup-environment]
      POSTGRES_HOST: postgres
      POSTGRES_EXTRA_OPTS: --blobs --format=custom --quote-all-identifiers
      BACKUP_SUFFIX: .backup
      HEALTHCHECK_PORT: 8080
    healthcheck:
      interval: 30s
  pgadmin:
    container_name: resolve_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      <<: [*admin-environment]
    ports:
      - *pgadmin-port
    volumes:
      - pgadmin-config:/pgadmin4-config
      - pgadmin:/var/lib/pgadmin
      - ${BACKUP_PATH}:/backups
    entrypoint: "/bin/sh"
    command: 
      - -c
      - |
        mkdir -p /var/lib/pgadmin/storage/$${PGADMIN_DEFAULT_EMAIL//@/_}/
        ln -s /backups /var/lib/pgadmin/storage/$${PGADMIN_DEFAULT_EMAIL//@/_}/
        /entrypoint.sh
    depends_on:
      - postgres
      - pgadmin-config
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/ || exit 1"]
  pgadmin-config:
    container_name: resolve_pgadmin-config-creator
    image: ghcr.io/elliotmatson/pgadmin-config-creator:latest
    restart: on-failure
    environment:
      <<: [*db-environment]
      PGADMIN_SERVER_JSON_FILE: /pgadmin4-config/servers.json
    volumes:
      - pgadmin-config:/config

volumes:
  pgadmin-config:
  pgadmin:
