---
name: Stack Healthcheck
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Deploy the stack, timeout if not healthy after 2m
        run: timeout 120 docker compose up --quiet-pull --wait
      - name: Check creating database
        run: docker compose logs | grep "CREATE DATABASE"
      - name: Check database creation
        run: docker compose logs | grep "Success. You can now start the database server"
      - name: Check postgres init
        run: docker compose logs | grep "PostgreSQL init process complete; ready for start up."